db:
  host: "${DB_HOSTNAME}"
  port: ${DB_PORT}
  name: "${DB_DATABASE_NAME}"
  user: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"

s3:
  are_local_buckets: true
  b2-eu-cen:
    key: "${MINIO_ROOT_USER}"
    secret: "${MINIO_ROOT_PASSWORD}"
    endpoint: "http://localhost:3200"
    region: "eu-central-2"
    bucket: "${S3_BUCKET}"